### ISSUE TITLE
XSRF doesn't work cause ctx.SetSecureCookie function on Beego 1.x

### ISSUE THREAD

**Issue by andyduong1920** [beego/beego#4369]
1. What version of Go and beego are you using (`bee version`)?
```
Go: 1.15.6
Beego: 1.12.3
```

2. What operating system and processor architecture are you using (`go env`)?
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/anduong/Library/Caches/go-build"
GOENV="/Users/anduong/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/anduong/.asdf/installs/golang/1.15.6/packages/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/anduong/.asdf/installs/golang/1.15.6/packages"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/anduong/.asdf/installs/golang/1.15.6/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/anduong/.asdf/installs/golang/1.15.6/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/anduong/workspace/personal/go/goMarketer/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/vr/58y62jvd0998d80x80pk0yz80000gn/T/go-build294748992=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

3. What did you do?
Enable XSRF on Beego following https://beego.me/docs/mvc/controller/xsrf.md

4. What did you expect to see?
The XSRF should work
1/ A `_xsrf` cookie
2/ When the POST form is submitted, it should process without any XSRF error

5. What did you see instead?
![image](https://user-images.githubusercontent.com/11751745/102337189-c10e1e80-3fc4-11eb-8d98-b624ad093a09.png)

6. Insight
It seems like because the `ctx.SetSecureCookie(key, "_xsrf", token, expire, "", "", true, true)` is wrong, it works with `ctx.SetSecureCookie(key, "_xsrf", token, expire, "", "")` and seems it has been fixed in version 2.0 https://github.com/beego/beego/commit/aec5f4b3a5d433092bc072b9b889f6697b4050a2#diff-701a591f92755498a3cef031183d2d2d7375cf953822bd0547ae80fcc583da03R153. 

With that said, on Beego 1.x we can't use that feature due the `ctx.SetSecureCookie(key, "_xsrf", token, expire, "", "", true, true)` issue 🤔

This is the Beego's XSRFToken function on my project 
![image](https://user-images.githubusercontent.com/11751745/102338000-ce77d880-3fc5-11eb-9e93-765caf00ecb4.png)

Thank you 🙏

**Comment by flycash** [comment]
When you upgrade to 1.12.3, the xsrf token only support for https protocol and it could not be read by JS. The last two parameter ( true, true) indicate that "httponly" and "secure" cookie.

One user had sent us email told that they were attacked due to unsecure cookie.
Please downgrade to 1.12.2 if you want to use xsrf. We are thinking about make "httponly" and "secure" configurable.

**Comment by flycash** [comment]
I prefer that using `EnableXSRF =false` when you are not in prod enviroment and using `EnableXSRF = true` in prod.

Don't forget to use https protocol.

Without those two flags, your applications are still not safe since someone could read token by JS.

**Comment by andyduong1920** [comment]
Yeah that make sense, should we update the documentation acroding the
changes on 1.12.3, that will avoid the confusion for new developer ☺️.

Another thing, I agreed that we should make it as configuration, can we
somehow having a small release 1.12.4 to support that, it will be great ♥️

I will close the issue for now, thank you for your reply and all the work
for Beego 🍻

**Comment by athom** [comment]
Hey, @flycash, @andyduong1920 

I am afraid your suggestion might not solve the issue. 
I can provide another reason that could be ignored. 
The fact is you set the _xsrf cookie with a empty("") cookie path, which makes it use the default path followed by the URI path. 

see 
https://datatracker.ietf.org/doc/html/rfc6265#section-5.2.4 
and 
https://datatracker.ietf.org/doc/html/rfc6265#section-5.1.4


The fifth params here is set to "", 
```go
ctx.SetSecureCookie(key, "_xsrf", token, expire, "", "", true, true)
```
Then the `_xsrf` cookie path property will be changed when URL is changes, 
say you are on a page with URL `xxx.com/a/b`, 
On the page, there is a form make a POST request to URL `xxx.com/c`. 
Then the cookie value of "_xsrf" also wont be fetched. 

A simple fixed will be put a "/" instead of ""

```
ctx.SetSecureCookie(key, "_xsrf", token, expire, "", "", true, true)
```

=>

```
ctx.SetSecureCookie(key, "_xsrf", token, expire, "/", "", true, true)
```
