### ISSUE TITLE
Why is not beego as fast as fiber ?

### ISSUE THREAD

**Issue by BlackGopher2020** [beego/beego#4419]
Hi, i wanna ask about the performance difference between beego framework and fiber according to this page 

https://github.com/the-benchmarker/web-frameworks

Now fiber is no.4 and beego is no.51

Why is there is a great difference between beego and fiber although both are using golang ?

Is it cuz of the size of the framework ?

And will beego be as fast as fiber in the future ?

I am a beginner in golang so forgive me for any ignorance

fiber 
https://gofiber.io/

**Comment by flycash** [comment]
We don't do any benchmark tests. For now, we think beego's performance is not good, but it's not bad. 
We will write more benchmark tests and then thinking about improving the performance.

**Comment by changsongl** [comment]
@BlackGopher2020 Thank you for pointing out the benchmark test. Fiber should be another light weight framework. For the benchmark tests, we know that it only testing the framework itself  without any real world logic, like searching Mysql and writing Redis. Once we write more logic for the apis, it will not have much difference between those frameworks. One reason behind the result is because Beego does provide more features than the lightweight framework. Feature is costing something. Another reason, I think we do have many things to improve, and we are working on it.
