### ISSUE TITLE
Orm for Oracle

### ISSUE THREAD

**Issue by evenliu** [beego/beego#4538]
I am now using Beego 2.0.0 on Windows 10, I find that in V1.6.1 you said that beego supported ORM with Oracle driver. 
But I don't find any document for this.
Where can I find some support documents for this update for Oracle driver.

**Comment by flycash** [comment]
As I known, in most cases, https://beego.me/docs/mvc/model/orm.md works for all drivers. The difference is that you should register your database by using "oracle" as driver.
```
	import (
		"fmt"
		"github.com/beego/beego/v2/client/orm"
		_ "github.com/go-sql-driver/mysql" //  change to oracle sql implementation
	)
orm.RegisterDataBase("default", "oracle", "oracle dsn", opts)
```
The problem is that I check source code and document, but I don't know which library should be used as Oracle driver.
I have confirm with other contributors, and no one remember that. :(

**Comment by flycash** [comment]
I will do some tests to find out the library when I am not busy.
