### ISSUE TITLE
`beego.gocn.vip` is clamied to be insecure 

### ISSUE THREAD

**Issue by Bishwas-py** [beego/beego#5399]
The official site of beego is claimed to be insecure `beego.gocn.vip`.
![image](https://github.com/beego/beego/assets/42182303/ba5771fe-81e8-4333-8d92-2955a984da95)

**Comment by kevineaton** [comment]
As of today, it still shows that. It also shows that the certificate expired nearly a year ago:
![image](https://github.com/beego/beego/assets/873989/84116f0e-635b-49ac-96b8-7dac6c610559)

I've never used Beego before and was going to try to experiment with it. The docs all seem to link to weird places in different locations. For example, the https://github.com/beego/beedoc repo links to http://beego.vip/docs in the README but that URL does not load for me. In the side panel, however, it links to http://beego.me/docs which then redirects to a site I don't recognize the language for, but is clearly not Beego.

**Comment by flycash** [comment]
https://github.com/beego/beego-doc the source code

**Comment by kevineaton** [comment]
But those docs point to the domain http://beego.vip/ which does not load and is http anyway.

**Comment by flycash** [comment]
I mean, you can read the source code directly, the maintainer of that website sometimes forget to renew the SSL certificate.

**Comment by kevineaton** [comment]
Reading the source code doesn't resolve the issues listed in this thread though. I could read the source, or I could read the docs as the source itself tells people to do. So other people in the community are reporting an issue with the docs that we cannot resolve with a PR.

To summarize, there are a few issues as I mentioned above. 

1) The SSL cert at https://beego.gocn.vip is nearly a year out of date on the original link posted. 
2) The other site (http://beego.vip/docs) is listed in the official docs repo but does not load at all; a PR can't be opened until the right site that is secure is communicated. This isn't an SSL renewal issue, the site just doesn't resolve.
3) Yet another site ((http://beego.me/docs) is listed in the official docs but now points to a completely unrelated site through a redirect. I would assume this is because it wasn't renewed and got squatted. As with 2 above, the link needs to be changed in the repo, but until a secure correct link is working, it's unclear where to go.

**Comment by arthurkay** [comment]
@flycash Why can't the project be hosted with github pages, that way github manages the SSL cert renewals.

**Comment by flycash** [comment]
All those developers who is from China are hard to access the Github due to the well-known GFW.
