### ISSUE TITLE
哈哈哈哈，项目的 token 直接明文写在 yaml 里面

### ISSUE THREAD

**Issue by phpyyds** [beego/beego#5497]
<img width="1066" alt="图片" src="https://github.com/beego/beego/assets/127014036/144067df-4df6-4532-930f-2a3a69e18268">

哈哈哈哈，项目的 token 直接明文写在 yaml 里面，xx项目。

**Comment by flycash** [comment]
This token is invalid. On one hand, it is incorrect itself, and on the other hand, as an open-source project, we don't need a token to upload code coverage reports.

I'm not sure what impact beego has had on you. If you lost your job or received criticism at work because of bugs in beego itself, then it's understandable for you to vent your emotions here.

If you have reported issues or submitted merge requests to us before, but we overlooked them, I apologize. Currently, the maintainers of this project are very busy and cannot keep an eye on it every day.

Meanwhile, I also hope that you can continue to help us improve this project, of course, using your regular GitHub account.
