### ISSUE TITLE
State Management with BeeGo Web Framework

### ISSUE THREAD

**Issue by CordialSocial** [beego/beego#5709]
GO/ Golang of itself, can handle backend effectively.

And when people these days want to build websites, they don't want to build something that is just simple-- else they will use something like **WordPress**, for a simple website.

The point is, if people want to commit time, hours and effort in coding a website from scratch, they actually want to build something **serious**, and with a lot of **interactivity**.

I mean, tools like **React**, **Vue**, and **Svelte** make it possible to create **Reusable Web Components**.

Their additional strong point is **State Management**-- where an application's components behaviour changes according to certain actions.

Can **BeeGo**  be upgraded to such height, as to provide the full features of tools like **React**, **Vue** and **Svelte**-- where we can create **Reusable Components**, as well as **State Management**-- in an easy to implement and easy to understand way?

Once **BeeGo** can be used to create **Reusable Web Components**, and BeeGo can handle **State Management** on the frontend, as well as cause these to be done in an easy to understand and easy to implement way, we would have brought the **React**, **Vue** and **Svelte** world to GO.

It will be nice if BeeGo can bring the full power of frontend -- which are **Reusable Web Components** and **State Management** capabilities to the world of GO.

The very things ( **Reusable Web Components** and **State Management** ) that make **React**, **Vue**, **Angular** and **Svelte** to be worth any mention.

Bring these same frontend capabilities to the GO Ecosystem.

**A POINT OF NOTE**
GO inherently can handle concurrency.

Use the concurrency feature of GO to manage **State** on a Web App developed with BeeGo.

What's the way forward on this?

Regards.

**Comment by flycash** [comment]
I personally think this looks not a good idea for these reasons:
-  As you can image that both Vue and React are complicated frameworks, and I don't think we have the ability build a similar one based on GO
- I am not sure if I got your point, I do notice that there are some toB companies (In China) are trying to provide some "reusable web framework". For example, they provide the user module with both frontend (including login, sign in, profile ...) and backend (including security solution, store...). However, they face many problems. For example, different style of pages, different user model...

If I have misunderstood your thoughts, please provide some specific examples so that I can understand.
